// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAssets():Promise<string>;

export function GetDefaultSharedWish():Promise<string>;

export function GetLanguage():Promise<string>;

export function GetLocale(arg1:string):Promise<string>;
