// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItems(arg1) {
  return window['go']['main']['App']['AddItems'](arg1);
}

export function Get4StarProgress(arg1, arg2) {
  return window['go']['main']['App']['Get4StarProgress'](arg1, arg2);
}

export function Get4Stars(arg1, arg2) {
  return window['go']['main']['App']['Get4Stars'](arg1, arg2);
}

export function Get5StarProgress(arg1, arg2) {
  return window['go']['main']['App']['Get5StarProgress'](arg1, arg2);
}

export function Get5Stars(arg1, arg2) {
  return window['go']['main']['App']['Get5Stars'](arg1, arg2);
}

export function GetPity(arg1, arg2) {
  return window['go']['main']['App']['GetPity'](arg1, arg2);
}

export function GetSharedWishName(arg1) {
  return window['go']['main']['App']['GetSharedWishName'](arg1);
}

export function GetSharedWishTypes() {
  return window['go']['main']['App']['GetSharedWishTypes']();
}

export function GetUIDs() {
  return window['go']['main']['App']['GetUIDs']();
}

export function GetWishName(arg1) {
  return window['go']['main']['App']['GetWishName'](arg1);
}
