// Code generated by `giwh gen menus`. DO NOT EDIT.

package hywiki

var (
	CharacterCards = Menu{
		ID:   17,
		Name: "Character Cards",
	}
	ActionCards = Menu{
		ID:   18,
		Name: "Action Cards",
	}
	EnemyandMonsterCards = Menu{
		ID:   19,
		Name: "Enemy and Monster Cards",
	}
	CharacterArchive = Menu{
		ID:   2,
		Name: "Character Archive",
	}
	NPCArchive = Menu{
		ID:   10,
		Name: "NPC Archive",
	}
	Weapons = Menu{
		ID:   4,
		Name: "Weapons",
	}
	Artifacts = Menu{
		ID:   5,
		Name: "Artifacts",
	}
	EnemiesandMonsters = Menu{
		ID:   7,
		Name: "Enemies and Monsters",
	}
	Wildlife = Menu{
		ID:   15,
		Name: "Wildlife",
	}
	TeyvatsResources = Menu{
		ID:   9,
		Name: "Teyvat's Resources",
	}
	Books = Menu{
		ID:   12,
		Name: "Books",
	}
	Tutorial = Menu{
		ID:   14,
		Name: "Tutorial",
	}
)

var Menus = []Menu{
	CharacterCards,
	ActionCards,
	EnemyandMonsterCards,
	CharacterArchive,
	NPCArchive,
	Weapons,
	Artifacts,
	EnemiesandMonsters,
	Wildlife,
	TeyvatsResources,
	Books,
	Tutorial,
}
