// Code generated by `giwh gen lang`. DO NOT EDIT.

package i18n

import "golang.org/x/text/language"

var (
	SimplifiedChinese = Language{
		Key:   "zh-cn",
		Name:  "简体中文",
		Short: "简",
	}
	TraditionalChinese = Language{
		Key:   "zh-tw",
		Name:  "繁體中文",
		Short: "繁",
	}
	German = Language{
		Key:   "de-de",
		Name:  "Deutsch",
		Short: "DE",
	}
	English = Language{
		Key:   "en-us",
		Name:  "English",
		Short: "EN",
	}
	Spanish = Language{
		Key:   "es-es",
		Name:  "Español",
		Short: "ES",
	}
	French = Language{
		Key:   "fr-fr",
		Name:  "Français",
		Short: "FR",
	}
	Indonesian = Language{
		Key:   "id-id",
		Name:  "Indonesia",
		Short: "ID",
	}
	Japanese = Language{
		Key:   "ja-jp",
		Name:  "日本語",
		Short: "JP",
	}
	Korean = Language{
		Key:   "ko-kr",
		Name:  "한국어",
		Short: "KR",
	}
	Portuguese = Language{
		Key:   "pt-pt",
		Name:  "Português",
		Short: "PT",
	}
	Russian = Language{
		Key:   "ru-ru",
		Name:  "Pусский",
		Short: "RU",
	}
	Thai = Language{
		Key:   "th-th",
		Name:  "ภาษาไทย",
		Short: "TH",
	}
	Vietnamese = Language{
		Key:   "vi-vn",
		Name:  "Tiếng Việt",
		Short: "VN",
	}
)

var Languages = []Language{
	SimplifiedChinese,  // zh-CN
	TraditionalChinese, // zh-TW
	German,             // de-DE
	English,            // en-US
	Spanish,            // es-ES
	French,             // fr-FR
	Indonesian,         // id-ID
	Japanese,           // ja-JP
	Korean,             // ko-KR
	Portuguese,         // pt-PT
	Russian,            // ru-RU
	Thai,               // th-TH
	Vietnamese,         // vi-VN
}

var Supported = []language.Tag{
	language.AmericanEnglish,    // en-US
	language.SimplifiedChinese,  // zh-Hans
	language.TraditionalChinese, // zh-Hant
	language.German,             // de-DE
	language.EuropeanSpanish,    // es-ES
	language.French,             // fr-FR
	language.Indonesian,         // id-ID
	language.Japanese,           // ja-JP
	language.Korean,             // ko-KR
	language.EuropeanPortuguese, // pt-PT
	language.Russian,            // ru-RU
	language.Thai,               // th-TH
	language.Vietnamese,         // vi-VN
}

var Matcher = language.NewMatcher(Supported)
