// Code generated by `giwh gen wishes`. DO NOT EDIT.

package wish

type Type int

const (
	NoviceWishes                             Type = 100
	PermanentWish                            Type = 200
	CharacterEventWish                       Type = 301
	CharacterEventWishAndCharacterEventWish2 Type = 301
	WeaponEventWish                          Type = 302
	CharacterEventWish2                      Type = 400
)

var Wishes = []Type{
	NoviceWishes,        // 100
	PermanentWish,       // 200
	CharacterEventWish,  // 301
	WeaponEventWish,     // 302
	CharacterEventWish2, // 400
}

var SharedWishes = []Type{
	NoviceWishes,                             // 100
	PermanentWish,                            // 200
	CharacterEventWishAndCharacterEventWish2, // 301
	WeaponEventWish,                          // 302
}
