// Code generated by `giwh gen wishes`. DO NOT EDIT.

package wish

var (
	NoviceWishes = Type{
		Key:  100,
		Name: "Novice Wishes",
	}
	PermanentWish = Type{
		Key:  200,
		Name: "Permanent Wish",
	}
	CharacterEventWish = Type{
		Key:  301,
		Name: "Character Event Wish",
	}
	CharacterEventWishAndCharacterEventWish2 = Type{
		Key:  301,
		Name: "Character Event Wish and Character Event Wish-2",
	}
	WeaponEventWish = Type{
		Key:  302,
		Name: "Weapon Event Wish",
	}
	CharacterEventWish2 = Type{
		Key:  400,
		Name: "Character Event Wish-2",
	}
)

var Wishes = []Type{
	NoviceWishes,        // 100
	PermanentWish,       // 200
	CharacterEventWish,  // 301
	WeaponEventWish,     // 302
	CharacterEventWish2, // 400
}

var SharedWishes = []Type{
	NoviceWishes,                             // 100
	PermanentWish,                            // 200
	CharacterEventWishAndCharacterEventWish2, // 301
	WeaponEventWish,                          // 302
}
