// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAssets() {
  return window['go']['main']['App']['GetAssets']();
}

export function GetDefaultSharedWish() {
  return window['go']['main']['App']['GetDefaultSharedWish']();
}

export function GetItems() {
  return window['go']['main']['App']['GetItems']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLocale(arg1) {
  return window['go']['main']['App']['GetLocale'](arg1);
}
