// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPity(arg1, arg2) {
  return window['go']['main']['App']['GetPity'](arg1, arg2);
}

export function GetProgress(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetProgress'](arg1, arg2, arg3);
}

export function GetPulls(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPulls'](arg1, arg2, arg3);
}

export function GetSharedWishName(arg1) {
  return window['go']['main']['App']['GetSharedWishName'](arg1);
}

export function GetSharedWishTypes() {
  return window['go']['main']['App']['GetSharedWishTypes']();
}

export function GetUIDs() {
  return window['go']['main']['App']['GetUIDs']();
}
