// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSharedWishTypes() {
  return window['go']['main']['App']['GetSharedWishTypes']();
}

export function Stat() {
  return window['go']['main']['App']['Stat']();
}
