// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPity(arg1:string,arg2:string):Promise<number>;

export function GetProgress(arg1:string,arg2:string,arg3:string):Promise<number>;

export function GetPulls(arg1:string,arg2:string,arg3:number):Promise<number>;

export function GetSharedWishName(arg1:string):Promise<string>;

export function GetSharedWishTypes():Promise<Array<string>>;

export function GetUIDs():Promise<Array<string>>;
